routes/web.php
<?php

use App\Http\Controllers\Expense\ExpenseController;
use App\Http\Controllers\Income\IncomeController;
use App\Http\Controllers\Income\NameController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/', [MainController::class, 'index'])->name('main');

    Route::post('/income', [IncomeController::class, 'store'])->name('income.store');

    Route::get('/income-name/create', [NameController::class, 'create'])->name('income-name.create');
    Route::post('/income-name/create', [NameController::class, 'store'])->name('income-name.store');

    Route::post('/expense', [ExpenseController::class, 'store'])->name('expense.store');

    Route::get('/expense-name/create', [\App\Http\Controllers\Expense\NameController::class, 'create'])->name('expense-name.create');
    Route::post('/expense-name/create', [\App\Http\Controllers\Expense\NameController::class, 'store'])->name('expense-name.store');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    {{ __("You're logged in!") }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/index.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Приложение учета доходов и расходов</title>
</head>
<body>

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('logout') }}" method="post">
    @csrf
    <input type="submit" value="Разлогиниться">
</form>

<h1>Capital - приложение учета доходов и расходов</h1>

<h3>Блок доходов</h3>

    @if($incomesNames->isEmpty())
        <p>Вы не создали ни одной статьи доходов</p>
    @else
        <form action="{{ route('income.store') }}" method="post">
            @csrf
            <select name="incomes_names_id">
                <option disabled selected value> -- выбери статью дохода -- </option>
                @foreach($incomesNames as $name)
                    <option value="{{ $name->id }}">{{ $name->name }}</option>
                @endforeach
            </select><br><br>
            <input type="number" step="0.01" name="total" placeholder="0.00"> рублей<br><br>
            <input type="submit" value="Добавить">
        </form>
    @endif

<p>Если в списке нет необходимой статьи доходов, то ее нужной <a href="{{ route('income-name.create') }}" target="_blank">Добвить</a></p>
<br><br>

<h3>Блок расходов</h3>

    @if($expensesNames->isEmpty())
        <p>Вы не создали ни одной статьи доходов</p>
    @else
        <form action="{{ route('expense.store') }}" method="post">
            @csrf
            <select name="expenses_names_id">
                <option disabled selected value> -- выбери статью расхода -- </option>
                @foreach($expensesNames as $name)
                    <option value="{{ $name->id }}">{{ $name->name }}</option>
                @endforeach
            </select><br><br>
            <input type="number" step="0.01" name="total" placeholder="0.00"> рублей<br><br>
            <input type="submit" value="Добавить">
        </form>
    @endif


<p>Если в списке нет необходимой статьи расходов, то ее нужной <a href="{{ route('expense-name.create') }}" target="_blank">Добавить</a></p>

<p><a href="">Переход на страницу вывода статистики</a></p>


</body>
</html>